In [1]:
import numpy as np
from scipy import sparse

In [2]:
#1.1 Creating a Vector
#Obj: Create a vector
#Soln: use np array to create 1-dim array

#creating vector as a row
vector_row = np.array([1,2,3])

#creating vector as a column
vector_column = np.array([[1],
                        [2],
                        [3]])

display(vector_row)
display(vector_column)

print('--*--')

print(vector_row)
print(vector_column)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

--*--
[1 2 3]
[[1]
 [2]
 [3]]


In [3]:
#1.2 Creating a Matrix
#Obj: Create a matrix
#Soln: using np to create a 2 dim array

#creating matrix
matrix = np.array([[1,2],
                   [3,4],
                   [5,6]])

display(matrix)
print('--*--')
print(matrix)

array([[1, 2],
       [3, 4],
       [5, 6]])

--*--
[[1 2]
 [3 4]
 [5 6]]


In [4]:
#for matrix object

matrix_object = np.mat([[1,2],
                       [3,4],
                       [5,6]])

display(matrix_object)
print('--*--')
print(matrix_object)

# matrix data structure is not recommended for two reasons
#1. arrays are the de facto standard data structure of NumPy
#2. vast majority of NumPy operations return arrays, not matrix objects

matrix([[1, 2],
        [3, 4],
        [5, 6]])

--*--
[[1 2]
 [3 4]
 [5 6]]


In [5]:
#1.3 Creating a Sparse Matrix
#Obj: given data with a large number of 0 values & a very few non-0 values, represent it efficiently
#Soln: creating a sparse matrix

#creating CSR (Compressed Sparse Row) matrix
matrix_sp=([[0,0],
           [0,1],
           [3,0]])
matrix_sparse = sparse.csr_matrix(matrix_sp)

display(matrix_sparse)
print('--*--')
print(matrix_sparse)

#A frequent situation in ML is having a huge amount of data; however, most of the elements in the data are zeros.
#Example- a matrix where :
   #columns - are every movie on Netflix 
   #rows - are every Netflix user
   #values - are how many times a user has watched that particular movie
#So, this matrix would have tens of thousands of columns and millions of rows! 
#However, since most users do not watch most movies, the vast majority of elements would be zero.

#Sparse matrices only store non-zero elements and assume all other values will be zero, 
#leading to significant computational savings. 
#In our solution, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. 
#If we view the sparse matrix we can see that only the nonzero values are stored

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

--*--
  (1, 1)	1
  (2, 0)	3


In [6]:
#there are many different types of sparse matrices, such as compressed sparse column, list of lists, and dictionary of keys.
#While an explanation of the different types and their implications is outside the scope of this book, it is worth noting that 
#while there is no “best” sparse matrix type, there are meaningful differences between them and we should be conscious about 
#why we are choosing one type over another

In [7]:
#1.4 Selecting Elements
#Obj: select one or more elements in a vector or matrix
#Soln: use np.array

#creating row vector
vector=np.array([1,2,3,4,5,6])

#creating matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#selecting 3rd element of row vector
vector[2]

3

In [8]:
#selecting 2nd row, 2nd column of matrix
matrix[1,1]

5

In [9]:
#slicing & dicing a matrix

In [10]:
#selecting all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [11]:
#selecting everything upto & including the 3rd element
vector[:3]

array([1, 2, 3])

In [12]:
#selecting everything after the 3rd element
vector[3:]

array([4, 5, 6])

In [13]:
#selecting the last element
vector[-1]

6

In [14]:
#select 1st two rows & all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#select all rows & 2nd column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [16]:
#1.5 Describing a Matrix
#Obj: describe the shape, size, and dimensions of the matrix
#Soln: use shape, size, ndim

matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

#to view number of rows & columns
matrix.shape

(3, 4)

In [17]:
#view number of elements (rows X columns)
matrix.size

12

In [18]:
#view number of dimensions
matrix.ndim

2

In [19]:
#1.6 Applying Operations to Elements
#Obj: applying function to multiple elements in an array
#Soln: use np.vectorize()

#creating matrix
matrix1 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#create a fun that add's 100 to an element
add_100 = lambda i:i+100

#creating a vectorized function
vectorized_add_100 = np.vectorize(add_100)

#applying function to all the elements in a matrix
vectorized_add_100(matrix1)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [20]:
#np.vectorize() class converts a function into a function that can be applied to all the elements in an array or slice of array.
#It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. 

#Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same 
#(a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

# Add 100 to all elements
matrix1 + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
#1.7 Finding the Maximum and Minimum Values
#Obj: finding min/max value in an array
#Soln: use np.max(), np.min()

matrix2 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#return max element
np.max(matrix2)

9

In [22]:
#return min element
np.min(matrix2)

1

In [23]:
#Obj: to find max/min value in an array or subset of an array
#Obj: applying the operation along a certain axis, using parameter- axis; axis=0 for column, axis=1 for rows

#Finding max element in each column
np.max(matrix2, axis=0)

array([7, 8, 9])

In [24]:
#Finding max element in each row
np.max(matrix2, axis=1)

array([3, 6, 9])

In [25]:
#1.8 Calculating the Average, Variance, and Standard Deviation
#Obj: calculate descriptive statistics about an array
#Soln: use np.mean(), np.var(), np.std

matrix3 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#calculate mean
np.mean(matrix3)

5.0

In [26]:
#calculating variance
np.var(matrix3)

6.666666666666667

In [27]:
#return standard deviation
np.std(matrix3)

2.581988897471611

In [28]:
#Finding descriptive stats about the whole matrix or doing calculations along a single axis

#Finding mean value in each column
np.mean(matrix3, axis=0)

array([4., 5., 6.])

In [29]:
#1.9 Reshaping Arrays
#Obj: transpose - change shape of an array (rows & columns) without changing element values
#Soln: use np.reshape

#creating 4X3 matrix
matrix4 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

#Transposing into 2X6 matrix
matrix4.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
#matrix.reshape() allows us to restructure an array so that we maintain the same data but it is organized as a different number 
#of rows and columns. 
#The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., the same size)

#To see the size of a matrix using matrix.size()
matrix4.size

12

In [31]:
#One useful argument in reshape is a combination of (-1,1) & (1,-1) which effectively means “as many as needed,” 
#reshape(-1, 1) means one row and as many columns as needed

matrix4.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
#reshape(1, -1) means as many rows as needed & one column 
matrix4.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [33]:
#if we provide one integer, reshape will return a 1D array of that length

matrix4.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
#1.10 Transposing a Vector or Matrix
#Obj: transpose a vector or matrix
#Soln: use matrix.T()

matrix4.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [35]:
#One nuanced point- technically, a vector cannot be transposed because it is just a collection of values

# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [36]:
#However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair 
#of brackets) or vice versa:

# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
#1.11 Flattening a Matrix
#Obj: transform a matrix in a one dim array
#Soln: use matrix.flatten()

matrix4.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
#to create a row shape vector
matrix4.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [39]:
#1.12 Finding the Rank of a Matrix
#Rank of a matrix is the dimensions of the vector space spanned by its columns or rows
#Obj: finding rank of a matrix
#Soln: use np's  linear algebra method matrix_rank

# Return matrix rank
np.linalg.matrix_rank(matrix4)

2

In [40]:
#1.13 Calculating the Determinant
#determinant is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the
#linear transformation described by the matrix
#Obj: find determinant of a matrix
#Soln:

matrix5 = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.linalg.det(matrix5)

0.0

In [41]:
#1.14 Getting the Diagonal of a Matrix
#Obj: get the diagonal elements of a matrix
#Soln:
matrix4.diagonal()

array([1, 5, 9])

In [42]:
matrix6 = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12],
                   [13,14,15,16,17,18],
                   [19,20,21,22,23,24]])

In [43]:
matrix6.diagonal()

array([ 1,  8, 15, 22])

In [44]:
matrix7 = np.array([[1,2,3,4,5,6,6.5],
                   [7,8,9,10,11,12,12.5],
                   [13,14,15,16,17,18,18.5],
                   [19,20,21,22,23,24,24.5]])

matrix7.diagonal()

array([ 1.,  8., 15., 22.])

In [45]:
#to get a diagonal off from the main diagonal by using the offset parameter
# Return diagonal one above the main diagonal
matrix4.diagonal(offset=1)

array([2, 6])

In [46]:
# Return diagonal one below the main diagonal
matrix4.diagonal(offset=-1)

array([ 4,  8, 12])

In [47]:
#1.15 Calculating the Trace of a Matrix
#The trace of a matrix is defined as the sum of its diagonal elements
#This can be shown to be equal to the sum of its eigenvalues

#Obj: Calculate trace of a matrix
#Soln:
matrix4.trace()

15

In [48]:
#We can also return the diagonal of a matrix and calculate its sum
sum(matrix4.diagonal())

15

In [49]:
#1.16 Finding Eigenvalues and Eigenvectors
#Eigenvectors are widely used in ML libraries. 
#Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vectors that, when that transformation 
#is applied, change only in scale (not direction). 
#More formally: A v = λ v 
#where A is a square matrix, λ contains the eigenvalues and v contains the eigenvectors. 
#In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix.


#Obj: find the eigenvalues and eigenvectors of a square matrix
#Soln: use np.linalg.eig(matrix)

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [50]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [51]:
#1.17 Calculating Dot Products
#Obj: calculate the dot product of two vectors
#Soln:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

In [52]:
# Amother operator for dot product
vector_a @ vector_b

32

In [53]:
#1.18 Adding and Subtracting Matrices
#Obj: add or subtract two matrices
#Soln:
matrix_a = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,2]])

matrix_b = np.array([[1,3,1],
                    [1,3,1],
                    [1,3,8]])

#Adding 2 matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [54]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [55]:
#Alternatively, use + and - operators

# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [56]:
#1.19 Multiplying Matrices
#Obj: multiplying two matrices
#Soln: use np.dot()

# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [57]:
#Alternatively, can use the @ operator
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [58]:
#For element-wise multiplication, we can use the * operator
matrix_a*matrix_b

array([[1, 3],
       [1, 4]])

In [59]:
#1.20 Inverting a Matrix
#Obj: calculate the inverse of a square matrix
#Soln:
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [60]:
#Creating identity matrix
#use linalg.inv to calculate A^(–1) if it exists --> multiply a matrix by its inverse and the result is the identity matrix

# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [61]:
#1.21 Generating Random Values
#Obj: generate pseudorandom values
#Soln: use np.random.random()

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [62]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [63]:
#Generating numbers by drawing them from a distribution
# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [64]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [65]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])